# Generated by Django 5.1.1 on 2024-10-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('ordered', 'Ordered')], default='ordered', max_length=20),
        ),
    ]
